import { useState, useEffect } from 'react';
import { getTestimonials, saveTestimonial, deleteTestimonial, type Testimonial } from '../../utils/adminStorage';
import { AdminForm } from './AdminForm';
import { DataTable } from './DataTable';
import { SEOFormFields } from './SEOFormFields';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import { Plus } from 'lucide-react';

export function ManageTestimonials() {
  const [testimonials, setTestimonials] = useState<Testimonial[]>([]);
  const [editingTestimonial, setEditingTestimonial] = useState<Testimonial | null>(null);
  const [isFormOpen, setIsFormOpen] = useState(false);

  useEffect(() => {
    loadTestimonials();
  }, []);

  const loadTestimonials = async () => {
    try {
      const data = await getTestimonials();
      setTestimonials(data);
    } catch (error) {
      console.error('Error loading testimonials:', error);
    }
  };

  const handleSave = async (testimonial: Testimonial) => {
    try {
      const saved = await saveTestimonial(testimonial);
      await loadTestimonials(); // Reload to get fresh data
      setIsFormOpen(false);
      setEditingTestimonial(null);
    } catch (error) {
      console.error('Error saving testimonial:', error);
      alert('Failed to save testimonial. Please try again.');
    }
  };

  const handleDelete = async (testimonial: Testimonial) => {
    if (confirm(`Are you sure you want to delete the testimonial from "${testimonial.name}"?`)) {
      try {
        await deleteTestimonial(testimonial.id);
        await loadTestimonials(); // Reload to get fresh data
      } catch (error) {
        console.error('Error deleting testimonial:', error);
        alert('Failed to delete testimonial. Please try again.');
      }
    }
  };

  const handleEdit = (testimonial: Testimonial) => {
    setEditingTestimonial(testimonial);
    setIsFormOpen(true);
  };

  const handleCancel = () => {
    setIsFormOpen(false);
    setEditingTestimonial(null);
  };

  const columns = [
    { key: 'name', label: 'Name' },
    { key: 'service', label: 'Service' },
    { 
      key: 'rating', 
      label: 'Rating',
      render: (item: Testimonial) => '⭐'.repeat(item.rating)
    },
    { key: 'date', label: 'Date' },
  ];

  if (isFormOpen) {
    return (
      <TestimonialForm
        testimonial={editingTestimonial}
        onSave={handleSave}
        onCancel={handleCancel}
      />
    );
  }

  return (
    <div className="space-y-6">
      <div className="mb-8">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h2 className="text-3xl font-bold text-charcoal mb-2">Testimonials</h2>
            <p className="text-gray-600">Manage customer testimonials</p>
          </div>
          <Button
            onClick={() => setIsFormOpen(true)}
            className="bg-blush-pink hover:bg-blush-pink-dark text-charcoal"
          >
          <Plus className="w-4 h-4 mr-2" />
          Add Testimonial
        </Button>
        </div>
      </div>

      <DataTable
        data={testimonials}
        columns={columns}
        onEdit={handleEdit}
        onDelete={handleDelete}
        keyExtractor={(t) => t.id}
      />
    </div>
  );
}

interface TestimonialFormProps {
  testimonial?: Testimonial | null;
  onSave: (testimonial: Testimonial) => void;
  onCancel: () => void;
}

function TestimonialForm({ testimonial, onSave, onCancel }: TestimonialFormProps) {
  const [formData, setFormData] = useState<Testimonial>(testimonial || {
    id: 0,
    name: '',
    service: '',
    rating: 5,
    text: '',
    date: new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
  });

  useEffect(() => {
    if (testimonial) {
      setFormData(testimonial);
    } else {
      // For new testimonials, let the database generate the ID
      setFormData({
        id: 0, // Will be generated by DB
        name: '',
        service: '',
        rating: 5,
        text: '',
        date: new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
      });
    }
  }, [testimonial]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData);
  };

  return (
    <AdminForm
      title={testimonial ? 'Edit Testimonial' : 'Add New Testimonial'}
      description="Add customer testimonials with SEO metadata"
      onSubmit={handleSubmit}
      onCancel={onCancel}
    >
      <div className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="name">Customer Name *</Label>
            <Input
              id="name"
              value={formData.name}
              onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="service">Service *</Label>
            <Input
              id="service"
              value={formData.service}
              onChange={(e) => setFormData(prev => ({ ...prev, service: e.target.value }))}
              required
            />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="rating">Rating *</Label>
            <select
              id="rating"
              value={formData.rating}
              onChange={(e) => setFormData(prev => ({ ...prev, rating: parseInt(e.target.value) }))}
              className="w-full h-9 px-3 rounded-md border border-input bg-input-background"
              required
            >
              {[1, 2, 3, 4, 5].map(r => (
                <option key={r} value={r}>{r} Star{r > 1 ? 's' : ''}</option>
              ))}
            </select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="date">Date *</Label>
            <Input
              id="date"
              value={formData.date}
              onChange={(e) => setFormData(prev => ({ ...prev, date: e.target.value }))}
              required
              placeholder="e.g., October 2025"
            />
          </div>
        </div>

        <div className="space-y-2">
          <Label htmlFor="text">Testimonial Text *</Label>
          <Textarea
            id="text"
            value={formData.text}
            onChange={(e) => setFormData(prev => ({ ...prev, text: e.target.value }))}
            required
            rows={5}
            placeholder="Customer testimonial text..."
          />
        </div>

        <SEOFormFields
          seoData={formData}
          onChange={(seoData) => setFormData(prev => ({ ...prev, ...seoData }))}
        />
      </div>
    </AdminForm>
  );
}

